services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_USER: "johana"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "parkingdb"
    ports:
      - "5432:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: "start-dev"