spring:
  application:
    name: parking
  datasource:
    url: jdbc:postgresql://localhost:5432/parking
    username: admin1
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/parking

server:
  port: 9081

logging:
  level:
    com.forero.parking: DEBUG

springdoc:
  swagger-ui:
    url: /open-api.yaml
openapi:
  aPIDocumentation:
    base-path: /parking

resilience4j.circuitbreaker:
  instances:
    emailCircuitBreaker:
      registerHealthIndicator: true
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
      permittedNumberOfCallsInHalfOpenState: 5
      minimumNumberOfCalls: 10
      automaticTransitionFromOpenToHalfOpenEnabled: true

base:
  url:
    micro:
      send-email: http://localhost:9080/mail/send