spring:
  application:
    name: parking
  datasource:
    url: jdbc:postgresql://localhost:5432/parking
    username: admin1
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/parking

server:
  port: 9081

logging:
  level:
    com.forero.parking: DEBUG

springdoc:
  swagger-ui:
    url: /open-api.yaml
openapi:
  aPIDocumentation:
    base-path: /parking

parking:
  global:
    cost-per-hour: 1000
    number-of-parking-lots: 100
