openapi: 3.0.2
info:
  title: API Documentation
  version: 1.0.0
servers:
  - url: http://localhost:9081/parking/
tags:
  - name: Parking
    description: Endpoints for user authentication and authorization
paths:
  /entrance:
    post:
      tags:
        - Parking
      summary: Register vehicle entry
      description: Register vehicle entry
      operationId: registerVehicleEntry
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParkingEntranceRequest'
      responses:
        200:
          description: The vehicle has entered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParkingEntranceResponse'
        400:
          description: Bad Request - If the resource is misspelled (badly constructed URI) If the data in the request is not correct.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
  /departure:
    post:
      tags:
        - Parking
      summary: Register vehicle exit
      description: Register vehicle exit
      operationId: registerVehicleExit
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParkingDepartureRequest'
      responses:
        200:
          description: The vehicle has exited successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParkingDepartureResponse'
        400:
          description: Bad Request - If the resource is misspelled (badly constructed URI) If the data in the request is not correct.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
  /vehicles:
    get:
      tags:
        - Parking
      summary: Vehicles currently in the parking
      description: Get the vehicles in the parking lot currently
      operationId: getVehiclesInParking
      security:
        - bearerAuth: [ ]
      responses:
        200:
          description: The vehicles have been listed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParkingVehiclesResponse'
  /email:
    post:
      tags:
        - Parking
      summary: Send email to vehicle owner
      description: Send email to vehicle owner
      operationId: sendEmail
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParkingEmailRequest'
      responses:
        200:
          description: Email was sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParkingEmailResponse'
        400:
          description: Bad Request - If the resource is misspelled (badly constructed URI) If the data in the request is not correct.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
  /:
    post:
      tags:
        - Parking
      summary: Create Parking
      description: Create parking only with the administrator role
      operationId: createParking
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParkingRequest'
      responses:
        200:
          description: The parking has entered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParkingResponse'
        400:
          description: Bad Request - If the resource is misspelled (badly constructed URI) If the data in the request is not correct.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ErrorObject:
      type: object
      additionalProperties: false
      properties:
        message:
          type: string
          description: Error message (detailed description)
          example: Invalid Request. Please, check the data in the request (QueryString Parameters and/or Body).
      description: Error details
      example:
        message: Invalid Request. Please, check the data in the request (QueryString Parameters and/or Body).
    ParkingEntranceRequest:
      required:
        - licensePlate
        - parkingLotId
      type: object
      description: Data required to enter a vehicle into the parking lot
      additionalProperties: false
      properties:
        licensePlate:
          $ref: '#/components/schemas/licensePlate'
        parkingLotId:
          $ref: '#/components/schemas/parkingLotId'
    ParkingEntranceResponse:
      required:
        - id
      type: object
      additionalProperties: false
      description: Response when a vehicle successfully enters the parking lot
      properties:
        id:
          type: integer
          format: int64
          description: record id
          example: 123456
    ParkingDepartureRequest:
      required:
        - licensePlate
        - parkingLotId
      type: object
      description: Data required to exit a vehicle into the parking lot
      additionalProperties: false
      properties:
        licensePlate:
          $ref: '#/components/schemas/licensePlate'
        parkingLotId:
          $ref: '#/components/schemas/parkingLotId'
    ParkingDepartureResponse:
      required:
        - totalPaid
      type: object
      additionalProperties: false
      description: Response when a vehicle successfully exits the parking lot
      properties:
        totalPaid:
          type: string
          description: total to paid
          example: 10,000.00
    ParkingVehiclesResponse:
      type: object
      required:
        - vehicles
      properties:
        vehicles:
          type: array
          items:
            $ref: '#/components/schemas/Vehicle'
      description: List of vehicles in the parking
    ParkingEmailRequest:
      required:
        - email
        - licensePlate
        - message
        - parkingName
      type: object
      description: Data required to send a email
      additionalProperties: false
      properties:
        email:
          type: string
          format: email
          description: Email address
          example: test@test.com
        licensePlate:
          $ref: '#/components/schemas/licensePlate'
        message:
          type: string
          description: Email message
          example: Parking lot entry.
        parkingName:
          type: string
          description: Parking name
          example: PARKING LOT HIRE ME
    ParkingEmailResponse:
      required:
        - message
      type: object
      additionalProperties: false
      description: Response when an email is sent successfully
      properties:
        message:
          type: string
          description: Email status message
          example: Email sent successfully
    Vehicle:
      required:
        - id
        - licensePlate
        - entranceDate
        - parkingLotId
      type: object
      additionalProperties: false
      description: Response when a vehicle successfully exits the parking lot
      properties:
        id:
          type: integer
          format: int64
          description: Vehicle id
          example: 123
        licensePlate:
          $ref: '#/components/schemas/licensePlate'
        entranceDate:
          type: string
          format: date-time
          description: Date of entry of the vehicle into the parking lot
          example: 2024-07-20T14:30:00Z
        parkingLotId:
          $ref: '#/components/schemas/parkingLotId'
    licensePlate:
      type: string
      maxLength: 6
      pattern: ^[a-zA-Z0-9]*$
      description: Vehicle license plate
      example: ABC123
    parkingLotId:
      type: integer
      format: int64
      description: Parking lot id
      example: 123
    ParkingRequest:
      required:
        - partnerId
        - parkingName
      type: object
      description: Data required to create parking
      additionalProperties: false
      properties:
        partnerId:
          type: string
          description: Partner id
          example: 123.oser.Avb
        parkingName:
          type: string
          description: Parking name
          example: PARKING LOT HIRE ME
    ParkingResponse:
      required:
        - parkingId
      type: object
      additionalProperties: false
      description: Response successfully and the parking lot Id
      properties:
        parkingId:
          type: integer
          description: parking id
          example: 123
